### ISSUE TITLE
handle "default" case

### ISSUE THREAD

**Issue by dcu** [nishanths/exhaustive#1]
currently the "default:" case is not handled well and the this checker asks to cover all cases even when default does that

**Comment by nishanths** [comment]
Thanks for the report. Setting the `-default-signifies-exhaustive` flag should provide the behavior you're looking for. Setting this flag will make the checker consider switch statements exhaustive as long as a `default` case is present, even if all enum members aren't explicitly listed in the switch.

The reported behavior was by design for the following reason. If it were not the default behavior, it would not be possible for the program to point out switch statements that may need to be updated when new enum members are added. (The existence of a `default` case does not necessarily mean that the existing switch doesn't need to be updated to account for the new enum members.)
