### ISSUE TITLE
Validate `map` keys the same way as `switch` cases

### ISSUE THREAD

**Issue by maratori** [nishanths/exhaustive#35]
There are places when we need to convert enum to some different value (enum or string, for example). 
Go's `map` is less verbose than `switch` and is more suitable for those cases.
Let's validate map keys with `exhaustive` linter.

Example
```go
type Enum int

const (
	A Enum = iota
	B
	C
)

func EnumToString_Switch(e Enum) string {
	switch e {
	case A:
		return "A"
	case B:
		return "B"
	case C:
		return "C"
	}
}

func EnumToString_Map(e Enum) string {
	return map[Enum]string{
		A: "A",
		B: "B",
		C: "C",
	}[e]
}
```

**Comment by maratori** [comment]
@nishanths I'd like to discuss comment association. Here #37 you said:

> In the long-term, it is better for the exhaustive program to align with go/ast's definition of associated comments for a node.

What do you think about following example?

```go
func EnumToString_Map(e Enum) string {
	//exhaustive:ignore
	return map[Enum]string{ //exhaustive:ignore
		A: "A",
		B: "B",
		C: "C",
	}[e]
}
```

According to `ast.NewCommentMap` both comments are not associated with map literal (`*ast.CompositeLit`).
The first one is associated with return statement.
And the second with `*ast.Ident` (`string` between `]` and `{`) 😮.

I've started development PR for this feature request, but don't know what is correct behavior.

Note: `golangci-lint` is ok with both comments (previous line and the same line).

**Comment by nishanths** [comment]
I think exhaustive should continue to follow `go/ast`’s definition for associated comments. 

For the first ignore comment, it appears that having it associated with the return statement could work out okay. Since the ignore comment is associated with the return statement, we can simply ignore checking of the entire return statement AST tree. The `Results` field of `ast.ReturnStmt` will include the map composite literal, which was originally desired to be ignored. 

So overall, we could special case return statements alone in this manner, for the user’s convenience (otherwise the map would have to be declared on its own line). 

Note that the above proposal makes it not possible to ignore/not ignore individual return values (i.e. only all of the return values can be ignored). But if a user needs that level of specificity, I think they should declare each return value separately and add comments to them individually. 

What do you think?

---

Relatedly, how are you currently planning to handle ignore comments placed next to a `var` declaration. Like:

    //exhaustive:ignore
    var x = map[K]V{ … } 

What node does `go/ast` associate this comment to?

**Comment by maratori** [comment]
I've created PR https://github.com/nishanths/exhaustive/pull/46 to support logic, you described.

**Comment by nishanths** [comment]
Apologies, I missed to respond to this thread earlier.

## Switch statements & expected behavior

In the following code, the expected behavior is that the switch statement should _not_ be ignored. This matches the current behavior in `master`. 

```go
func DoSomething(e Enum) string {
	//exhaustive:ignore
	if true {
		switch e {
		case A:
			return "A"
		case B:
			return "B"
		}
	}
}
```

But if the ignore comment is moved, such that the ignore comment is associated (as defined by package `go/ast`) with the `ast.SwitchStmt`, like in the following code, then the expected behavior is that the switch statement should be ignored. This, too, matches the current behavior and tests in `master`.

```go
func DoSomething(e Enum) string {
	if true {
		//exhaustive:ignore
		switch e {
		case A:
			return "A"
		case B:
			return "B"
		}
	}
}
```

Finally, if a switch statement is nested inside an ignored switch statement, the nested switch statements isn't affected by the outer ignore comment. See this [illustrative test case][1], whose code is reproduced below.

```go
func _nested() {
	var d Direction

	// this should not report.
	//exhaustive:ignore
	switch d {
	case N:
	case S:
	case W:
	default:
		// this should report.
		switch d { // want "^missing cases in switch of type Direction: E, directionInvalid$"
		case N:
		case S:
		case W:
		default:
		}
	}
}
```

On your question:

> Am I right that this applies to switch as well (now it's not)?

Based on the above, the answer would be no. The current behavior in `master` is already the expected behavior. So I'm afraid  changes in #46 isn't the desired behavior. Sorry again for missing to reply in this thread earlier!

## Maps

For maps, there is no clear defintion of "associated", as there is for switch statements. Switch statements have a dedicated `ast.SwitchStmt` node, whereas maps do not.

So my proposal is the following: If an ignore comment is associated with `ast.GenDecl`, `ast.DeclStmt`, or `ast.ReturnStmt`, ignore this node and its entire subtree.

> What is the special-case?

The special-case was that, for maps, in addition to checking for ignore comments on `ast.GenDecl` and `ast.DeclStmt`, we also check for ignore comments on `ast.ReturnStmt`. By including return statements, it would allow to write code like:

```go
//exhaustive:ignore
return map[X]Y{ ... }
```

instead of having to do:

```go
//exhaustive:ignore
tmp := map[X]Y{ ... }
return tmp
```

[1]: https://github.com/nishanths/exhaustive/blob/b974ba36a6133a82c651cecc0a86a7c08e5595ae/testdata/src/ignore-comment/ignore_comment.go#L47-L65

**Comment by maratori** [comment]
Thanks, now it's clear to me.
I'll try to prepare PR to support maps.

**Comment by maratori** [comment]
@nishanths may I ask you to release a new version with this feature?

**Comment by nishanths** [comment]
of course! i will tag a new version today.

**Comment by nishanths** [comment]
I created a new tag `v0.8.3` that should include these changes. To check map literals for exhaustiveness, the `-check` flag must include `"map"`. For example:

```
exhaustive -check=switch,map
```
