### ISSUE TITLE
What if I have include some cases in default?

### ISSUE THREAD

**Issue by MuyaoXiao** [nishanths/exhaustive#6]
For example, I have:
```go
type OS int 

const (
Windows OS = iota
Darwin
Linux
BSD
)
```
and I want to write something like:
```go
case something {
case darwin:
    fmt.Println("MacOS")
default:
   panic("something")
}
```
However, this will be reported as non-exhaustive.
Should I add something duplicate like below?
```go
case Windows, Linux, BSD:
    panic("something")
case default:
    panic("something")
```

**Comment by nishanths** [comment]
Correct, you would have to add duplicate cases as in the last code snippet. It was am intentional design decision  to require listing all enum values explicitly for the switch to be considered exhaustive, even if a `default` case is present. 

However if the `-default-signifies-exhaustive` flag is set, then the behavior changes, and the first switch statement also will be considered exhaustive. 

```
-default-signifies-exhaustive
    	indicates that switch statements are to be considered exhaustive if a 'default' case
    	is present, even if all enum members aren't listed in the switch (default false)
```

**Comment by MuyaoXiao** [comment]
Thanks a lot!
