### ISSUE TITLE
Doesn't detect iota enums without type annotation

### ISSUE THREAD

**Issue by yaseenkadir** [nishanths/exhaustive#62]
When enum values are declared using ` = iota`, exhaustive is unable to detect it without the type annotation.

For example
```go
// not detected in switches
type IotaEnumNoTypes uint8
const (
	EnumOneNoTypes = iota
	EnumTwoNoTypes
)
```

```go
// gets detected
type IotaEnum uint8
const (
	EnumOne IotaEnum = iota
	EnumTwo
)
```
NOTE the `EnumOne IotaEnum = iota`

<details>
<summary>Can run exhastive against this sample demo file to reproduce</summary>

```go
package abc

import "fmt"

type IotaEnum uint8

const (
	EnumOne IotaEnum = iota
	EnumTwo
)

func iotaEnumToStr(enum IotaEnum) string {
	switch enum {
	case EnumOne:
		return "one"
	}
	return "none"
}

type IotaEnumWithTypes uint8

const (
	EnumOneWithType IotaEnumWithTypes = iota
	EnumTwoWithType IotaEnumWithTypes = 1
)

func iotaEnumWithTypeToStr(enum IotaEnumWithTypes) string {
	switch enum {
	case EnumOneWithType:
		return "one"
	}
	return "none"
}

type IotaEnumNoTypes uint8

const (
	EnumOneNoTypes = iota
	EnumTwoNoTypes
)

func iotaEnumNoTypeToStr(enum IotaEnumNoTypes) string {
	switch enum {
	case EnumOneNoTypes:
		return "one"
	}
	return "none"
}

func main() {
	fmt.Println(iotaEnumToStr(EnumOne))
	fmt.Println(iotaEnumWithTypeToStr(EnumOneWithType))
	fmt.Println(iotaEnumNoTypeToStr(EnumOneNoTypes))
}
```

Output:
```
main.go:13:2: missing cases in switch of type abc.IotaEnum: abc.EnumTwo
main.go:28:2: missing cases in switch of type abc.IotaEnumWithTypes: abc.EnumTwoWithType
```
</details>

**Comment by nishanths** [comment]
Thanks for the report. This is working as expected. `EnumOneNoTypes` and `EnumTwoNoTypes` are of type `int`, and are not of the named type `IotaEnumNoTypes`. `exhaustive` doesn't consider these variables to be enum values, because the variables are not of a named type.

Related docs \[1]:

> For the purpose of this analyzer, and by convention, an enum type is any named type [...] has at least one constant of its type defined in the same block.

The linked Go playground \[2] prints the types for the variables above. 

\[1]: https://pkg.go.dev/github.com/nishanths/exhaustive#hdr-Definition_of_enum
\[2]: https://go.dev/play/p/3moCQtmJx71
