### ISSUE TITLE
Feature Request: Allow specifying that a type isn't an enum

### ISSUE THREAD

**Issue by iwahbe** [nishanths/exhaustive#76]
The definition of an enum specified by [your docs](https://pkg.go.dev/github.com/nishanths/exhaustive#section-documentation) includes cases where user's might not want exhaustive analysis to be enforced. I encountered this in a case similar to this:

```go
package token

type Token string

...

const SpecialValue Token = "_"
```

In the example, `Token` isn't an enum: it has an arbitrary number of valid values. Some code switches on `Token` looking for certain values, but there is never an expectation to be exhaustive. `exhaustive` defines `Token` as an enum with the single value `SpecialValue` and so throws false positives.

I can add `//exhaustive:ignore` to downstream locations that consume `Token`, but that pushes the burden onto users of my type. It also forces me to declare that `Token` isn't an enum in multiple places.

I would like to be able to tell exhaustive to ignore a type or a constant value. Both of these syntaxes make sense to me:

```go
//exhaustive:ignore
type Token string
```

```go
//exhaustive:ignore
const SpecialValue Token = "_"
```

Let me know if this change works for you. If you are amenable, I would be happy to open a PR.

**Comment by nishanths** [comment]
Thanks for the issue. Yes, the change works for me. It would be good for package authors to have the ability to declare that a type or a constant defined in their own package isn't an enum type or an enum member, such that package users downstream can benefit from this declaration. Secondly, it would be good to have the ability to make these declarations directly in source code, rather than only via the `-ignore-enum-types`/`-ignore-enum-members` flags, which could grow stale (e.g. the type definition could be removed from source, but the type name could still be specified in the flag value).

The syntax in the issue description makes sense to me.

Possibly on an unrelated note, can you clarify what you mean by the following quote? Do you mean having had to add `//exhaustive:ignore` at multiple switch statements that switched on a value of type Token?

> It also forces me to declare that Token isn't an enum in multiple places.
